# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'

#  [plugins.build]
#  windows = 'tools\\update-dll-mingw'
#  cygwin  = 'make -f make_cygwin.mak'
#  mac     = 'make -f make_mac.mak'
#  linux   = 'make'
#  unix    = 'gmake'

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

# Nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'

# Markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

# Japanese doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

# solarized
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# Tomorrow-Night-Thema 
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'


# indentLine
[[plugins]]
repo = 'Yggdroot/indentLine'

# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'
repo = 'The-NERD-Commenter'

# シングルクオートとダブルクオートの入れ替え等csコマンド
[[plugins]]
repo = 'tpope/vim-surround'

# その他便利機能
[[plugins]]
repo = 'Townk/vim-autoclose'
repo = 'itchyny/lightline.vim'
repo = 'thinca/vim-quickrun'




# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
#[[plugins]]
# repo = 'elzr-vim-json'
# if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
